name: Analyze

on:
  push:
    tags: [ "v*.*.*" ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
  branch_protection_rule:
  schedule:
  - cron: '15 7 * * 2'

# Declare default permissions as read-only.
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install Actionlint
      env:
        # renovate: datasource=github-releases depName=rhysd/actionlint
        ACTIONLINT_VERSION: 1.7.7
      run: .github/scripts/install-actionlint.sh

    - name: Run Actionlint
      run: actionlint

  ossf-scorecard:
    runs-on: ubuntu-24.04
    if: github.ref_name == github.event.repository.default_branch || github.event_name == 'pull_request'
    permissions:
      security-events: write
      id-token: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Run analysis
      uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde # v2.4.2
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: ${{ github.ref_name == github.event.repository.default_branch }}
