name: GHCR Maintenance

on:
  schedule:
  - cron: '30 1 * * *'
  workflow_dispatch:

# Declare default permissions as read-only.
permissions: read-all

jobs:
  cleanup:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: Cleanup Untagged Images
      uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
      with:
        delete-untagged: true
        delete-ghost-images: true
        delete-partial-images: true
        delete-orphaned-images: true

    - name: Cleanup >7d Old Images
      uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
      with:
        exclude-tags: "latest,*.*.*"
        delete-tags: "pr-*,build-*"
        older-than: 7 days
